name: Process new TCX

on:
  push:
    paths:
      - 'data/**/*.tcx'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      MAX_POWER: 250
      STABLE_WINDOW_S: 30
      STABLE_STD_THRESHOLD: 5
      MIN_STABLE_DURATION_S: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Validate env secret
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL secret is missing" >&2
            exit 1
          fi

      - name: Export env vars from secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Process all new TCX files
        run: |
          set -e
          for f in data/*.tcx; do
            if [ ! -f "$f" ]; then
              echo "No TCX file found in data/; skipping."
              continue
            fi
            echo "=== Processing $f ==="

            parser_output=$(python src/ingest/parser.py --input "$f" 2>&1)
            echo "$parser_output" | tee parser_output.log

            # extrait session ID fiable (que ce soit nouveau ou déjà existant)
            SESSION_ID=$(echo "$parser_output" | grep -E '^SESSION_ID:' | head -n1 | cut -d':' -f2 | tr -d '\r\n')
            if [ -z "$SESSION_ID" ]; then
              # fallback sur ALREADY_PROCESSED si jamais
              SESSION_ID=$(echo "$parser_output" | grep -E '^ALREADY_PROCESSED' | head -n1 | awk '{print $2}' | tr -d '\r\n')
            fi

            if [ -z "$SESSION_ID" ]; then
              echo "Could not extract session ID for $f; parser output:" >&2
              echo "$parser_output" >&2
              exit 1
            fi
            echo "Extracted session ID: $SESSION_ID"

            # lancer l'analyse sur cette session
            python src/processing/analysis.py --session-id "$SESSION_ID"
          done
