name: Process new TCX

on:
  push:
    paths:
      - 'data/**/*.tcx'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      MAX_POWER: 250
      STABLE_WINDOW_S: 30
      STABLE_STD_THRESHOLD: 5
      MIN_STABLE_DURATION_S: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate DATABASE_URL secret
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL is missing" >&2
            exit 1
          fi

      - name: Export DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Process TCX files
        run: |
          set -euo pipefail
          mkdir -p data/processed
          for f in data/*.tcx; do
            [ -f "$f" ] || continue
            base=$(basename "$f")
            marker="data/processed/${base}.done"
            if [ -f "$marker" ]; then
              echo "✅ $base already processed"
              continue
            fi

            echo "➤ Processing $base"
            out=$(python src/ingest/parser.py --input "$f")
            echo "$out"
            sid=$(echo "$out" | grep -Po '(?<="session_id": ")[^"]+')
            if [ -z "$sid" ]; then
              echo "❌ Could not extract session_id"
              exit 1
            fi
            echo "Session ID: $sid"

            python src/processing/analysis.py --session-id "$sid"

            touch "$marker"
          done
