name: Process new TCX

on:
  push:
    paths:
      - 'data/**/*.tcx'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      MAX_POWER: 250
      STABLE_WINDOW_S: 30
      STABLE_STD_THRESHOLD: 5
      MIN_STABLE_DURATION_S: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package in editable mode
        run: |
          pip install --upgrade pip
          pip install -e .  # installe le projet via pyproject.toml

      - name: Validate env secret
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL secret is missing" >&2
            exit 1
          fi

      - name: Export env vars from secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      
      - name: Process all new TCX files
        run: |
          set -euo pipefail
          for f in data/*.tcx; do
            if [ ! -f "$f" ]; then
              echo "No TCX file found in data/; skipping."
              continue
            fi
            echo "=== Processing $f ==="

            python src/ingest/parser.py --input "$f" | tee parser_output.log

            # extraire le premier UUID valide (session) et le nettoyer
            SESSION_ID=$(grep -Eo '[0-9a-fA-F-]{36}' parser_output.log | head -n1 | tr -d '\r\n')
            if [ -z "$SESSION_ID" ]; then
              echo "Could not extract session ID for $f; check parser output."
              cat parser_output.log
              exit 1
            fi
            echo "Extracted session ID: $SESSION_ID"

            # lancer l'analyse sur cette session
            python src/processing/analysis.py --session-id "$SESSION_ID"
          done

